---
# handlers file for ansible-role-ubuntu-hardening
- name: ensure restart the openssh server
  systemd:
    name: ssh
    state: restarted
    enabled: true
  listen: "restart ssh"

- name: ensure apply sysctl configurations
  systemd:
    name: systemd-sysctl
    state: restarted
    enabled: true
  listen: "restart sysctl"

- name: ensure restart openntpd
  systemd:
    name: openntpd
    state: restarted
    enabled: true
  listen: "restart openntpd"

- name: ensure daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
    name: daemon_reload
  listen: "daemon_reload"
